config/routes.rb
X::Application.routes.draw do

  devise_for :users, :controllers => {:users => "registrations"}
  resources :tool_types

  resources :project_types

  root :to => 'home#hello'
  
  match 'home' => 'home#hello', :via => :get, :as => :home
  match 'search' => 'search#search', :via => [:get, :post], :as => :search
  match 'sign_in' => 'users#new', :via => :get, :as => :sign_in
  match 'user/:id' => 'user_view#show', :via => :get, :as => :show_user

  resources :tools
  match 'tool/:name' => 'tools#tool_view', :via => :get, :as => :tool_detail
  
  resources :projects
  match 'github' => 'projects#github', :via => [:get, :post], :as => :github
  match 'gh_create' => 'projects#gh_create', :via => :post, :as => :gh_create
end

app/controllers/tool_types_controller.rb
class ToolTypesController < ApplicationController
  before_action :set_tool_type, only: [:show, :edit, :update, :destroy]

  # GET /tool_types
  # GET /tool_types.json
  def index
    @tool_types = ToolType.all
  end

  # GET /tool_types/1
  # GET /tool_types/1.json
  def show
    @tools = @tool_type.tools
  end

  # GET /tool_types/new
  def new
    @tool_type = ToolType.new
  end

  # GET /tool_types/1/edit
  def edit
  end

  # POST /tool_types
  # POST /tool_types.json
  def create
    @tool_type = ToolType.new(tool_type_params)

    respond_to do |format|
      if @tool_type.save
        format.html { redirect_to @tool_type, notice: 'Tool type was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tool_type }
      else
        format.html { render action: 'new' }
        format.json { render json: @tool_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tool_types/1
  # PATCH/PUT /tool_types/1.json
  def update
    respond_to do |format|
      if @tool_type.update(tool_type_params)
        format.html { redirect_to @tool_type, notice: 'Tool type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tool_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tool_types/1
  # DELETE /tool_types/1.json
  def destroy
    @tool_type.destroy
    respond_to do |format|
      format.html { redirect_to tool_types_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tool_type
      @tool_type = ToolType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tool_type_params
      params.require(:tool_type).permit(:name, :description)
    end
end

app/helpers/tool_types_helper.rb
module ToolTypesHelper
end

app/views/tool_types/_form.html.erb
<%= form_for(@tool_type) do |f| %>
  <% if @tool_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tool_type.errors.count, "error") %> prohibited this tool_type from being saved:</h2>

      <ul>
      <% @tool_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tool_types/edit.html.erb
<h1>Editing tool_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @tool_type %> |
<%= link_to 'Back', tool_types_path %>

app/views/tool_types/index.html.erb
<h1>Types of Tools</h1>

<div class="row">
  <% @tool_types.each do |tool_type| %>
      <div class="col-xs-4" style="height: 350px; overflow: hidden;">
        <h2><%= link_to tool_type.name, tool_type %></h2>
        <p class="lead"><%= tool_type.description[0..300] + '...' %></p>
        <div id="sk_ac">
          <div><%= link_to 'Edit', edit_tool_type_path(tool_type) %></div>
          <div><%= link_to 'Destroy', tool_type, method: :delete, data: { confirm: 'Are you sure?' } %></div>
        </div>
      </div>
      <div class="clearfix visible-xs-block"></div>
  <% end %>
</div>

<%= link_to 'New Tool Type', new_tool_type_path %>

app/views/tool_types/new.html.erb
<h1>New tool_type</h1>

<%= render 'form' %>

<%= link_to 'Back', tool_types_path %>

app/views/tool_types/show.html.erb
<%= stylesheet_link_tag 'tools' %>

<h1><%= @tool_type.name.pluralize %></h1>

<div class="detail_description">
  <%= @tool_type.description %>
</div>

<div class="btn btn-default">
  <%= link_to 'Edit Tool Type', edit_project_type_path(@tool_type) %>
</div>

<% unless @tool_type.tools.empty? %>
    <h2><%= @tool_type.name.pluralize @tool_type.tools.count %> Tools</h2>
    <%= render 'shared/tools_list', :tools => @tools %>
<% end %>