config/routes.rb
X::Application.routes.draw do

  devise_for :users, :controllers => {:users => "registrations"}
  resources :tool_types

  resources :project_types

  root :to => 'home#hello'
  
  match 'home' => 'home#hello', :via => :get, :as => :home
  match 'search' => 'search#search', :via => [:get, :post], :as => :search
  match 'sign_in' => 'users#new', :via => :get, :as => :sign_in
  match 'user/:id' => 'user_view#show', :via => :get, :as => :show_user

  resources :tools
  match 'tool/:name' => 'tools#tool_view', :via => :get, :as => :tool_detail
  
  resources :projects
  match 'github' => 'projects#github', :via => [:get, :post], :as => :github
  match 'gh_create' => 'projects#gh_create', :via => :post, :as => :gh_create
end

app/models/project.rb
class Project < ActiveRecord::Base
  include PgSearch

  belongs_to :project_type

  has_many :projects_tools, :inverse_of => :project, autosave: true
  has_many :tools, :through => :projects_tools

  has_many :users_projects, :inverse_of => :project, autosave: true
  has_many :users, :through => :users_projects

  accepts_nested_attributes_for :projects_tools, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
  accepts_nested_attributes_for :tools, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true

  attr_accessible :name, :description, :projects_tools, :project_type_id, :owner, :project_type, :external
  validates :name,
            :project_type_id,
            #:owner,
            :description, presence: true
            
  multisearchable :against => [:description, :name]
end

app/models/project_type.rb
class ProjectType < ActiveRecord::Base
  include PgSearch
  
  has_many :projects

  attr_accessible :name, :description
  validates :name, :description, presence: true
  
  #multisearchable :against => [:name, :description]
  multisearchable :against => [:description, :name]
end

app/controllers/projects_controller.rb
require 'tool'

class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.all.order :name
  end

  def show
    @tools = @project.tools
  end

  def new   
    @project = Project.new
    @project.projects_tools.build
    @tools = Tool.all.order :name
    @tool_types = ToolType.all.order :name
  end
  
  def github
    
  end

  class GitHubProjectImporter
    attr_accessor :repo_owner, :repo_name

    def initialize(repo_path)
      args = repo_path.split('/')
      @repo_owner = args[0]
      @repo_name = args[1]
    end

    def read_me
      HTTParty.get "https://api.github.com/repos/#{repo_path}/readme?client_id=#{@client_id}&client_secret=#{@client_secret}"
    end

    def read_me_decoded
      Base64.decode64(read_me.parsed_response['content'])
    end

    def gem_file
      HTTParty.get "https://api.github.com/repos/#{repo_path}/contents/Gemfile?client_id=#{@client_id}&client_secret=#{@client_secret}"
    end

    def gem_file_decoded
      Base64.decode64(gem_file.parsed_response["content"]).to_s.gsub('"',"'").to_s.gsub("\n",' ').to_s.gsub(",",' ')
    end

    def project
      result = Project.new
      result.name = repo_name
      result.owner = repo_owner
      result.external = true
      result.project_type = ProjectType.where(:name => 'Web Application').first
      result.description = read_me_decoded
      result
    end

    def gems
      unless gem_file.parsed_response['content'].nil?
        gem_array = gem_file_decoded.scan(/gem \'.*?\'/)
        result = Array.new
        gem_array.each do |gem|
          gem = /\'.*?\'/.match(gem)
          result << gem.to_s.gsub("'",'')
        end
        result
      else
        nil
      end
    end

    private
      @client_id = ENV['GITHUB_CLIENT_ID']
      @client_secret = ENV['GITHUB_CLIENT_SECRET']

      def repo_path
        "#{repo_owner}/#{repo_name}"
      end
  end

  def gh_create
    unless params['gh_user_repo'].blank?
      importer = GitHubProjectImporter.new(params['gh_user_repo'])
      @gem_project =  importer.project
      @gems = importer.gems
      create
    else
      redirect_to github_path
    end
  end

  def edit
    @existing_tools = Array.new
    @project.projects_tools.each do |t|
      @existing_tools << t.tool_id
    end
    @tools = Tool.all.order :name
    @tool_types = ToolType.all.order :name
  end

  def create
    @project = @gem_project || Project.new(:name => params[:project][:name],
          :owner => current_user[:username],
          :description => params[:project][:description],
          :project_type_id => params[:project][:project_type_id])
    
    @tool_types = ToolType.all.order :name

    respond_to do |format|
      if @project.save

        UsersProject.new(:user => current_user, :project => @project).save

        set_tools

        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def set_tools
    selected_tools
    new_tools
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        set_tools
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(
          :name,
          :owner,
          :description,
          :project_type_id,
          :projects_tools_attributes => [:project_id, :tool_id, :notes, :_destroy])
    end
    
    def new_tools
      begin
        if @gem_project.nil?
          params[:project][:tool].require(:name, :description)
        end
      rescue ArgumentError
        return
      end
      if @gem_project.nil?
        unless save_tool(params[:project][:tool]).nil?
          project_tool = ProjectsTool.find_or_create_by(:project_id=>@project.id ,:tool_id=>@tool.id)
        end
      elsif !@gems.nil?
        @gems.each do |g|
          save_gh_tool(g)
          project_tool = ProjectsTool.find_or_create_by(:project_id=>@project.id ,:tool_id=>@tool.id)
        end
      end
    end
    
    def selected_tools
      params.each do |k,v|
        if v.is_a?(String) and v == "on"
          ProjectsTool.find_or_create_by(project_id: @project.id, tool_id: k)
        end
      end 
    end
    
    def save_tool(tool_params)
      @tool = Tool.find_by(name: tool_params[:name]) || Tool.find_by(ugly_name: tool_params[:name])
      if @tool.nil?
        @tool = Tool.create(tool_params)
      end
    end
    
    def save_gh_tool(gem)
      @tool = Tool.find_by(name: gem) || Tool.find_by(ugly_name: gem)
      if @tool.nil?
        tool_type = ToolType.where(:name => 'Scripting Language').first
        @tool = Tool.create(:name => gem, :description => 'Ruby gem', :tool_type => tool_type)
      end
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project, html:{class:"well"}) do |f| %>
                
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="project_details">
	  <div class="field">
	    <%= f.label :project_name, 'Project Name:' %><br>
	    <%= f.text_field :name, :class => "form-control" %>
	  </div>
    <div class="field">
      <%= f.label :project_type_id, 'Project Type:' %><br>
      <%= f.collection_select :project_type_id, ProjectType.all, :id, :name, {prompt: true}, {class: "form-control"} %>
    </div>
	  <div class="field">
	    <%= f.label :project_description, 'How was this project crafted?' %><br>
	    <%= f.text_area :description, :class => "form-control", :rows => "10" %>
	  </div>
  </div>
  <div id="project_tools" class="field">
    Tools:
		<div id="tools_list"><%= render 'shared/tools_list_for_project' %></div>
		<div id="new_tool"><%= render 'shared/tools_adder', :f => f %></div>
  </div>
  <%= f.submit class: "btn btn-primary btn-lg form-submit", "role" => "button" %>

<% end %>

app/views/projects/_project_list.html.erb
<%= stylesheet_link_tag params[:controller] %>


<h1 class="page-heading">Projects</h1>
<%= link_to 'Add Project', new_project_path, class: 'btn btn-primary btn-lg' %>

<% if @projects.blank? || @projects.length <= 0 %>
    <h1>:-(</h1>

<% else %>
    <% (0..@projects.length/3).each do |row_count| %>
        <div class="row">

          <% col_count = 0 %>
          <% while col_count < 3 %>
              <% project = @projects.all[(row_count * 3) + col_count] %>
              <% if project.present? %>

                  <div class="col-sm-6 col-md-4">
                    <div class="card-content card-height">
                      <h2><%= link_to project.name, project %></h2>
                      <p><%= project.description[0..100] + '...' %></p>
                      <div class="small-scroll">
                        <% project.tools[0..8].each do |tool| %>
                            <%= link_to tool.name, tool, class: "btn btn-info", "role" => "button" %>
                        <% end %>
                      </div>
                    </div>
                  </div>

              <% else %>
                  <% break %>
              <% end %>

              <% col_count += 1 %>
          <% end %>
        </div>
    <% end %>
<% end %>

app/views/projects/edit.html.erb
<%= stylesheet_link_tag "edit_project" %>

<h1 class="page-heading">Editing Project</h1>
<div class="edit-links">
  <%= link_to 'Back', projects_path, {class: "btn btn-default"} %>
  <%= link_to 'Go To Project', @project, {class: "btn btn-primary"} %>
</div>

<%= render 'form' %>

app/views/projects/github.html.erb
<%= form_tag gh_create_path do %>
  <div class="form-group">
	<b>Github Project</b>
	<br/>
	username/repo:
  	<input name="gh_user_repo" id="user_repo" type="text" autofocus="autofocus" class="form-control" />
  </div>
  
  <%= submit_tag 'make it so', class: 'btn btn-primary btn-lg form-submit' %>

<% end %>
		

app/views/projects/index.html.erb
<h1 class="page-heading">Projects</h1>
<%= link_to 'Add Project', new_project_path, class: 'btn btn-primary btn-lg' %>

<%= render partial: 'shared/project_list' %>

app/views/projects/new.html.erb
<h2>New Project</h2>

	<%= link_to 'Create from Github', github_path, class:"btn btn-primary btn-lg" %>
	<br/>
	<br/>	
	<b>Or:</b>
	<br/>
	<br/>
	
<%= render 'form' %>

app/views/projects/show.html.erb
<%= stylesheet_link_tag 'show_project' %>
<%= stylesheet_link_tag 'tools' %>


<div class="col-xs-10 page-heading-inline">
  <h1><%= @project.name %>
    <span class="badge">
      <%= link_to @project.project_type.name, project_type_path(@project.project_type) %>
    </span>
  </h1>

<% if @project.external %>

	<h4>Project Owner: <u><%= link_to @project.owner, "https://github.com/#{@project.owner}", :target => "_blank" %></u></h4>
    <h4><%= link_to "view on GitHub", "https://github.com/#{@project.owner}/#{@project.name}", :target => "_blank" %></h4>
<% else %>
    <h4>Project Participants:
      <%= @project.users.map{ |user| link_to user.username, "/user/#{user.id}"}.join(', ').html_safe %>
    </h4>
<% end %>
</div>

<div class="col-xs-2"><%= link_to 'Edit Project', edit_project_path(@project), role: "button", class: "btn btn-primary edit", style:"float:right" %></div>

<div class="col-xs-12 detail_description well">
  <%= raw(markdown @project.description) %>
</div>

<% unless @project.projects_tools.empty? %>
  <div class="col-xs-12">
  <h2 class="page-header">Tools</h2>
  <%= render 'shared/tools_list' %>
  </div>
<% end %>