config/routes.rb
X::Application.routes.draw do

  devise_for :users, :controllers => {:users => "registrations"}
  resources :tool_types

  resources :project_types

  root :to => 'home#hello'
  
  match 'home' => 'home#hello', :via => :get, :as => :home
  match 'search' => 'search#search', :via => [:get, :post], :as => :search
  match 'sign_in' => 'users#new', :via => :get, :as => :sign_in
  match 'user/:id' => 'user_view#show', :via => :get, :as => :show_user

  resources :tools
  match 'tool/:name' => 'tools#tool_view', :via => :get, :as => :tool_detail
  
  resources :projects
  match 'github' => 'projects#github', :via => [:get, :post], :as => :github
  match 'gh_create' => 'projects#gh_create', :via => :post, :as => :gh_create
end

app/views/layouts/_nav.html.erb
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-49144351-2', 'careerbox.herokuapp.com');
    ga('send', 'pageview');

</script>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Folio: Build &amp; Tell</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if params[:controller] != "home" %>
        <li class="<%= 'active' if current_page?(projects_path) %>"><%= link_to 'Projects', projects_path %></li>
        <li class="<%= 'active' if current_page?(tools_path) %>"><%= link_to 'Tools', tools_path %></li>
        <% end %>
        <li class="<%= 'active' if current_page?(home_path) %>">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user[:username]%> <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li>
                <%= link_to('Sign Out', destroy_user_session_path, :method => :delete) %>
              </li>
              <li>
                <%= link_to('Edit Registration', edit_user_registration_path) %>
              </li>
            </ul>
          </li>
        <% else %>
            <li>
              <%= link_to('Sign In', new_user_session_path) %>
            </li>
            <li>
              <%= link_to('Register', new_user_registration_path)  %>
            </li>
        <% end %>
        <%= form_tag(search_path, :method => :get, :id => 'search-form', class: 'navbar-form navbar-left', role: 'search') do %>
          <div class="form-group">
            <input name="search_params" id="search_term" type="text" autofocus="autofocus" class="form-control" placeholder="Search" value="<%= params["search_params"] %>" />
          </div>
          <%= submit_tag 'Go', class:'btn btn-default' %>
        <% end %>
        </li>
      </ul>

    </div>
  </div>
</nav>

app/views/layouts/_reveal.html.erb
<style type="text/css">
  #debug_container {width: 1200px; color: #000000; background: #FFFFFF; word-wrap:break-word; text-indent: 3%; margin-bottom: 30px;}
  #debug_container .debug_tab_header  {
      float: left;
      cursor: pointer;
      border: 1px solid red;
      color: #535353;
      background: #FFFFFF;
      width: 30%;
      height: 30px;
      padding: 5px;
  }
  #debug_container .debug_tab_active {
      color: #FFCC40;
      background: #535353;
      text-shadow: 1px 1px 1px #000000;
      filter: dropshadow(color=#000000, offx=1, offy=1);
      -webkit-box-shadow: inset 0px 0px 10px 0px #000000;
      box-shadow: inset 0px 0px 10px 0px #000000;
  }
  #debug_container .debug_tab {
      display: none;
      color: #FFCC40;
      border-top: 1px solid #CCCCCC;
      border-bottom: 1px solid #000000;
      text-shadow: 1px 1px 1px #000000;
      filter: dropshadow(color=#000000, offx=1, offy=1);
  }
  #debug_container .debug_tab_header:hover {
      color: #FFCC40;
      background: #535353;
      text-shadow: 1px 1px 1px #000000;
      filter: dropshadow(color=#000000, offx=1, offy=1);
      -webkit-box-shadow: inset 0px 0px 10px 0px #000000;
      box-shadow: inset 0px 0px 10px 0px #000000;
  }
  #debug_container .debug_right_tab {
      -webkit-border-radius: 0px 8px 0px 0px;
      border-radius: 0px 8px 0px 0px;
  }
  #debug_container .row {
      width: 100%;
      padding-bottom: 10px;
      margin: 0px;
  }
  #debug_container .sub_row {
      width: 100%;
      border-bottom: 1px solid #000000;
      background: #2d2d2d;
      color: #CCCCCC;
      font-size: 0.8em;
      font-weight: bold;
  }
  #debug_container .key {
      width: 100%;
      padding:  5px 0px;
      border-bottom: 1px solid #000000;
      background: #2d2d2d;
      color: #CCCCCC;
      font-size: 1em;
      font-weight: bold;
  }
  #debug_container .value {
      width: 96%;
      margin: 0 auto;
      padding:  5px 0px;
      border-bottom: 1px solid #535353;
      text-shadow: 1px 1px 1px #000000;
      filter: dropshadow(color=#000000, offx=1, offy=1);
      color: #FFCC40;
      background: #535353;
  }
  #debug_container .sub_key {
      width: 100%;
      padding:  4px 0px;
      border-bottom: 1px solid #000000;
      background: #CCCCCC;
      color: #2d2d2d;
      font-size: 1em;
      font-weight: bold;
      text-shadow: 0px 0px 0px #000000;
      filter: dropshadow(color=#000000, offx=0, offy=0);
  }
  #debug_container .debug_content {
      width: 90%;
      margin: 0 auto;
      padding: 0px !important;
      border: 1px solid #2d2d2d;
      -webkit-box-shadow:  0px 0px 20px 1px #000000;
      box-shadow:  0px 0px 20px 1px #000000;
  }
  #debug_container .debug_dropdown {
      cursor: pointer;
      display: block;
  }
  #debug_container .debug_tab_content_wrapper {
      width: 100%;
      background: #535353;
      overflow: auto;
  }
  .debug_count {
    float: right;
    border: 1px solid #FFCC40;
    margin-right: 2%;
    margin-top: -2px;
    padding: 3px 7px 1px 2px;
    -webkit-border-radius: 15px 15px 8px 8px;
    border-radius: 15px 15px 8px 8px;
  }
</style>
<script type="text/javascript">
  $(function(){
     $('.debug_tab_header').on('click', function(){
        $('.debug_tab').each(function(){$(this).hide();});
        $('.debug_tab_header').each(function(){$(this).removeClass('debug_tab_active');});
        $(this).addClass('debug_tab_active');
        $tab = $(this).attr('tab');
        $('#'+$tab).show();
     });
     $('.debug_dropdown').on('click', function(){
        $(this).next().toggle();
     });
  });
</script>
<div class="clearfix"></div>
<br /><br />
<div id="debug_container" class="clearfix">
    <div class="debug_tabs clearfix">
      <div class="debug_tab_header" tab="debug_params">Params</div>
      <div class="debug_tab_header debug_right_tab" tab="debug_session">Session</div>
    </div>
    <div class="debug_tab_content_wrapper clearfix">
        <div class="debug_tab clearfix" id="debug_params">
          <% params.each do |k,v|%>
              <div class="row">
                <% unless v.kind_of?(Hash) %>
                    <div class="key"><%= k %></div>
                    <div class="value"><%= v %></div>
                <% else %>
                    <div class="key debug_dropdown"><%= k %></div>
                    <div class="value debug_content">
                      <% v.each do |k,v| %>
                          <div class="sub_row clearfix">
                            <div class="sub_key"><%= k %></div>
                            <div class="value"><%= v %></div>
                          </div>
                      <% end %>
                    </div>
                <% end %>
              </div>
          <% end %>
        </div>
        
        <div class="debug_tab clearfix" id="debug_session">
          <div class="clearfix"></div>
          <% session.to_hash.each do |k,v| %>
            <div class="row">
            <% unless v.kind_of?(Hash) %>
                <div class="key"><%= k %></div>
                <div class="value"><%= v %></div>
            <% else %>
             <div class="key debug_dropdown"><%= k %></div>
             <div class="value debug_content">
              <% v.each do |k,v| %>
                <div class="sub_row clearfix">
                  <div class="sub_key"><%= k %></div>
                  <div class="value"><%= v %></div>
                </div>
              <% end %>
             </div>
          <% end %>
          </div>
        <% end %>
      </div>
      
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Folio - Build and Tell</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body id="body_container" class="clearfix">



    <%= render 'layouts/nav' %>

    <div class="container">

      <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
      <% end %>
        <%= yield %>
        <!--
        <h1>Bootstrap starter template</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
        -->
    </div>

    <%# if Rails.env.development?%>
    <% if false %>
        <div id="rd">
            <%= render 'layouts/reveal' %>
        </div>
    <% end %>

</body>
</html>